insert into persona (nombre,direccion,edad) values ('persona1','direccion1',1)
insert into persona (nombre,direccion,edad) values ('persona2','direccion2',2)
insert into persona (nombre,direccion,edad) values ('persona3','direccion3',3)
insert into persona (nombre,direccion,edad) values ('persona4','direccion4',4)
insert into persona (nombre,direccion,edad) values ('persona5','direccion5',5)